const vehicles=[{name:'Porsche 911 Carrera',type:'sport',price:8500,img:'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1000&q=85'},{name:'BMW M4 Competition',type:'sport',price:6500,img:'https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=1000&q=85'},{name:'Nissan GT-R',type:'sport',price:7500,img:'https://images.unsplash.com/photo-1544636331-e26879cd4d9b?auto=format&fit=crop&w=1000&q=85'},{name:'BMW S 1000 RR',type:'bike',price:4200,img:'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?auto=format&fit=crop&w=1000&q=85'},{name:'Kawasaki Ninja ZX-10R',type:'bike',price:3800,img:'https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?auto=format&fit=crop&w=1000&q=85'},{name:'Ducati Panigale V4',type:'bike',price:5000,img:'https://images.unsplash.com/photo-1566274361635-0f1f2e4f0f0e?auto=format&fit=crop&w=1000&q=85'}];
let currentType='all';
function renderVehicles(type='all'){currentType=type;const grid=document.getElementById('vehicleGrid');const empty=document.getElementById('emptyState');const list=vehicles.filter(v=>type==='all'||v.type===type);grid.innerHTML=list.map(v=>`<article class="vehicle-card"><img src="${v.img}" alt="${v.name}" loading="lazy"><div class="vehicle-info"><p>${v.type==='sport'?'SPORTS CAR':'BIG BIKE'}</p><h3>${v.name}</h3><p>พร้อมให้เช่า • ตรวจเช็กก่อนส่งมอบ</p><p class="price">฿${v.price.toLocaleString()} <small>/ วัน</small></p><button class="btn primary" onclick="bookVehicle('${v.name}')">จองรถคันนี้</button></div></article>`).join('');empty.hidden=list.length>0;}
function filterVehicles(type){renderVehicles(type);document.getElementById('fleet').scrollIntoView({behavior:'smooth'});}
function showAllVehicles(e){if(e)e.preventDefault();renderVehicles('all');}
function searchFleet(){const type=document.getElementById('searchType').value;const p=document.getElementById('pickupDate').value;const r=document.getElementById('returnDate').value;if(p&&r&&new Date(r)<new Date(p)){showToast('วันคืนรถต้องไม่ก่อนวันรับรถ');return}renderVehicles(type);document.getElementById('fleet').scrollIntoView({behavior:'smooth'});showToast('แสดงรถที่ตรงกับเงื่อนไขแล้ว');}
function bookVehicle(name){const p=document.getElementById('pickupDate').value;const r=document.getElementById('returnDate').value;if(!p||!r){document.getElementById('pickupDate').focus();showToast('กรุณาเลือกวันรับและวันคืนรถก่อน');return}if(new Date(r)<new Date(p)){showToast('วันคืนรถไม่ถูกต้อง');return}const days=Math.max(1,Math.ceil((new Date(r)-new Date(p))/86400000));const v=vehicles.find(x=>x.name===name);const total=v.price*days;showToast(`จอง ${name} ${days} วัน • ฿${total.toLocaleString()}`);}
function openMemberModal(){document.getElementById('memberModal').classList.add('show');document.getElementById('memberModal').setAttribute('aria-hidden','false');}
function closeMemberModal(){document.getElementById('memberModal').classList.remove('show');document.getElementById('memberModal').setAttribute('aria-hidden','true');}
function registerMember(e){e.preventDefault();const name=document.getElementById('memberName').value;localStorage.setItem('driveXMember',name);closeMemberModal();showToast(`สมัครสมาชิกสำเร็จ ยินดีต้อนรับคุณ ${name}`);e.target.reset();}
function showToast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.classList.remove('show'),3200);}
window.addEventListener('click',e=>{if(e.target.id==='memberModal')closeMemberModal()});
document.addEventListener('DOMContentLoaded',()=>{renderVehicles();const today=new Date().toISOString().split('T')[0];document.getElementById('pickupDate').min=today;document.getElementById('returnDate').min=today;document.getElementById('pickupDate').addEventListener('change',e=>document.getElementById('returnDate').min=e.target.value);});